### ISSUE TITLE
Está prevista internacionalização?

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#15]
https://github.com/lab-ds/crm-lab-team/blob/154f893601c0bfe8567eb99506d2896cfb7afafa/src/main/java/br/edu/ifrs/canoas/lds/webapp/domain/CaseMotive.java#L5-L9

**Comment by FelipeEmerim** [comment]
Sim, estes textos são na verdade códigos de mensagens do arquivo messages.properties. No front end eles são representados e retornam a representação textual do enum no idioma correto.
