### ISSUE TITLE
Tem que fazer - Botar os fragments na aba Atividades

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#51]
https://github.com/lab-ds/crm-lab-team/blob/02a9e7fec9fb0fd6c77f5a8422b2e8e3f2a2f17f/src/main/resources/templates/task/index.html#L100-L122

**Comment by gusalles** [comment]
Eu não tenho nada pra botar na aba de atividades, acha melhor eu só tirar?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by rodrigonoll** [comment]
Não, tem que colocar os cases que tem tasks, os files que tem tasks, a mesma coisa que os colegas fizeram. Nessa página, você consolida e cruza as informações de tasks que estão vinculadas em outros objetos. Tem que manter.

**Comment by gusalles** [comment]
Eu achava que quem criou o fragmento tinha que botar nas páginas, pelo menos eu fiz isso com o meu. Mas eu arrumo aqui.

**Comment by rodrigonoll** [comment]
Tem razão, passa a issue para o responsável, por favor. Quem fez o objeto
tem que fazer o fragmento, assim como fez com o seu. Muda a issue
direcionando,ok?

Em dom, 12 de mai de 2019 00:25, Gustavo Alles <notifications@github.com>
escreveu:

**Comment by rodrigonoll** [comment]
Só reforçando, tem que ter esses objetivos nas atividades.

**Comment by NikolasDaroit** [comment]
Na aba de atividade de Contas, já incluí  Contatos e Casos

**Comment by FelipeEmerim** [comment]
Inseri o fragmento de casos nas telas que faltavam
