### ISSUE TITLE
Definir um padrão para nomenclatura das chaves.

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#58]
https://github.com/lab-ds/crm-lab-team/blob/e38b502041ca8f4ef633539fe8b2e78bfc96e3a9/src/main/resources/messages.properties#L1-L474

**Comment by rodrigonoll** [comment]
A última palavra é maiúscula ou minúscula?

**Comment by FelipeEmerim** [comment]
Para enums estamos utilizando a última palavra maiúscula conforme a Carina mencionou para você na aula. As demais mensagens permanecem com a última palavra minúscula
