### ISSUE TITLE
/** Documentar todas as classes com autor, propósito e data de criação (vide github). **/

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#59]

**Comment by rodrigonoll** [comment]
Se o método de autor diferente do da classe, descrever o autor.

**Comment by FelipeEmerim** [comment]
O padrão seria esse: 

https://github.com/lab-ds/crm-lab-team/blob/8e83bba80ca04eccf175b340a835b5a645e6ab90/src/main/java/br/edu/ifrs/canoas/lds/webapp/controller/LeadController.java#L34-L38

**Comment by rodrigonoll** [comment]
excelente

--

Atenciosamente,

*Prof. Dr. Rodrigo Noll*
Professor de Engenharia de Software e Programação
Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Sul -
IFRS - Campus Canoas
Rua Dra. Maria Zélia Carneiro de Figueiredo, 870-A
Bairro Igara III - CEP 92412-240 - Canoas/RS
Fone: (51) 3415.8200– Ramal: 220
E-mail: rodrigo.noll@canoas.ifrs.edu.br
Website: http://www.canoas.ifrs.edu.br



Em seg, 13 de mai de 2019 às 13:48, FelipeEmerim <notifications@github.com>
escreveu:

**Comment by Carinaemerim** [comment]
Documentei as classes relativas a Leads.

**Comment by gusalles** [comment]
Documentei as classes relativas a task.
