### ISSUE TITLE
Organizar Imports

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#6]
https://github.com/lab-ds/crm-lab-team/blob/4d7e5eeeacfecfe7cdddb6c77f1be9271373d7f3/src/main/java/br/edu/ifrs/canoas/lds/webapp/controller/FileController.java#L9-L10

**Comment by mauricioblum** [comment]
@rodrigonoll

**Comment by rodrigonoll** [comment]
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
