### ISSUE TITLE
Use lombok Builder 

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#60]
https://github.com/lab-ds/crm-lab-team/blob/e8278c5860437480c6a7942a73014c9b3f7d1c38/src/main/java/br/edu/ifrs/canoas/lds/webapp/service/ContactService.java#L40-L46

**Comment by rodrigonoll** [comment]
https://projectlombok.org/features/Builder

**Comment by MiguelRebelatto** [comment]
Não é um novo objeto
