### ISSUE TITLE
Colocar em um ControllerAdvice

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#68]
https://github.com/lab-ds/crm-lab-team/blob/e8278c5860437480c6a7942a73014c9b3f7d1c38/src/main/java/br/edu/ifrs/canoas/lds/webapp/controller/ContactController.java#L59-L71

**Comment by FelipeEmerim** [comment]
Corrigido em 3177ca721211561741846065f77ac2396e779308
