### ISSUE TITLE
Remover código não utilizado

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#7]
https://github.com/lab-ds/crm-lab-team/blob/4d7e5eeeacfecfe7cdddb6c77f1be9271373d7f3/src/main/java/br/edu/ifrs/canoas/lds/webapp/controller/FileController.java#L108

**Comment by rodrigonoll** [comment]
em todas as instâncias

**Comment by mauricioblum** [comment]
@rodrigonoll
