### ISSUE TITLE
Externalize em um ControllerAdvice https://rodrigonoll.github.io/aula/java-spring/#/3/30

### ISSUE THREAD

**Issue by rodrigonoll** [lab-ds/crm-lab-team#70]
https://github.com/lab-ds/crm-lab-team/blob/9d23b6b928ff1de116888b82233696edd61c883e/src/main/java/br/edu/ifrs/canoas/lds/webapp/controller/LeadController.java#L49-L61

**Comment by FelipeEmerim** [comment]
Foi corrigido em 3177ca721211561741846065f77ac2396e779308
